import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";

// const designio = localFont({
//   src: "./fonts/DesignioBold.woff",
//   variable: "--font-designio",
//   weight: "100 900",
// });

// const designioRegular = localFont({
//   src: "./fonts/DesignioRegular.woff",
//   variable: "--font-designio-regular",
//   weight: "100 900",
// });

// const designioMedium = localFont({
//   src: "./fonts/DesignioMedium.woff",
//   variable: "--font-designio-medium",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${designio.variable} ${designioRegular.variable}  ${designioMedium.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
