import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const designio = localFont({
  src: [
    { path: "./fonts/DesignioRegular.woff", weight: "400", style: "normal" },
    { path: "./fonts/DesignioMedium.woff", weight: "400", style: "normal" },
    { path: "./fonts/DesignioBold.woff", weight: "400", style: "normal" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ designio.className}>{children}</body>
    </html>
  );
}
